name: Repo Smoke Test

# Temp disable this owrks i tink update
# on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.19.0

      - name: Install pnpm
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Test - pnpm dev for 5s
        run: timeout 5 pnpm dev || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - name: Test - pnpm lint
        run: pnpm lint

      - name: Test - pnpm build
        run: pnpm build

      - name: Test - pnpm format
        run: pnpm format
