# This is a basic workflow to help you get started with Actions

name: Repo Smoke Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.19.0

      - name: Install pnpm
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Test - pnpm dev for 5s
        run: timeout 5 pnpm dev || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - name: Test - pnpm lint
        run: pnpm lint

      - name: Test - pnpm build
        run: pnpm build

      - name: Test - yarn format
        run: yarn format

      - name: Test - yarn lint
        run: yarn lint
